sonar.projectKey=L50E02O_NexusFlow
sonar.organization=l50e02o

sonar.projectName=NexusFlow
sonar.sources=.

sonar.sourceEncoding=UTF-8

sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**
sonar.test.exclusions=**/*.test.ts,**/*.test.tsx,**/*.spec.ts,**/*.spec.tsx